{
    "name": "CRM SIPROC Flow",
    "version": "19.0.1.0.1",
    "summary": "Flujo comercial SIPROC y automatización básica de prospección",
    "category": "Sales/CRM",
    "author": "SIPROC",
    "website": "https://siprocgt.com",
    "license": "LGPL-3",
    "depends": ["crm", "mail", "contacts"],
    "data": [
        "security/security.xml",
        "security/ir.model.access.csv",
        "data/stage_data.xml",
        "data/mail_activity_data.xml",
        "data/cron_data.xml",
        "views/crm_lead_views.xml",
        "views/crm_prospect_log_views.xml",
        "views/crm_prospect_rule_views.xml",
        "views/crm_prospect_dashboard_views.xml",
        "wizards/prospect_import_wizard_views.xml",
    ],
    "installable": True,
    "application": False,
}
